version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: myblog-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpwd}
      MYSQL_DATABASE: ${DB_NAME:-myshkin451blog}
      MYSQL_USER: ${DB_USER:-bloguser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-blogpass}
    volumes:
      - /data/mysql:/var/lib/mysql  
    networks:
      - blog-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    image: ghcr.io/achernar-eridani/blog-backend:${TAG:-latest}
    container_name: myblog-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production  
      DB_HOST: db
      DB_USER: ${DB_USER:-bloguser}
      DB_PASSWORD: ${DB_PASSWORD:-blogpass}
      DB_NAME: ${DB_NAME:-myshkin451blog}
      JWT_SECRET: ${JWT_SECRET:-your-production-secret}
      PORT: 3000
      BASE_URL: https://myshkin451.com  
    volumes:
      - ./uploads:/app/uploads  
    networks:
      - blog-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: ghcr.io/achernar-eridani/blog-frontend:${TAG:-latest}
    container_name: myblog-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - blog-network
    restart: unless-stopped

networks:
  blog-network:
    driver: bridge

