version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: blog-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: myshkin451blog
      MYSQL_USER: bloguser
      MYSQL_PASSWORD: blogpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.dev
    container_name: blog-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_USER: bloguser
      DB_PASSWORD: blogpass
      DB_NAME: myshkin451blog
      JWT_SECRET: devsecret
      PORT: 3000
      BASE_URL: http://localhost:3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules        # 不覆盖依赖
      - ./uploads:/app/uploads
    command: ["node", "app.js"]
    env_file:
      - .env.docker

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.frontend.dev
    container_name: blog-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: ["npm", "run", "dev", "--", "--host"]

  adminer:
    image: adminer
    container_name: blog-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
